#caching modules
cache:
    paths:
      - node_modules/
      - .yarn
  

staging_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus staging."
        - docker rm -f ffc_janus || true
        - docker build -t 3bot_app_jimber/ffc_janus:staging .
        - docker run -d -it --name=ffc_janus --network=ffc 3bot_app_jimber/ffc:staging
    
deploy:
    stage: deploy
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus production."
        - docker rm -f ffc_janus || true
        - docker build -t 3bot_app_jimber/ffc_janus:$CI_COMMIT_TAG .
        - docker run -d -it --name=ffc_janus --network=ffc 3bot_app_jimber/ffc_janus:$CI_COMMIT_TAG
    