cache:
    paths:
      - node_modules/
      - .yarn

stages:
    - build
    - deploy

staging_build:
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc_janus staging."
        - docker build -t jimber/ffc_janus_gateway:staging-$CI_COMMIT_TAG .
        - docker push jimber/ffc_janus_gateway:staging-$CI_COMMIT_TAG

staging_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcstaging
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc_janus staging."
        - docker pull jimber/ffc_janus_gateway:staging-$CI_COMMIT_TAG
        - docker rm -f ffc_janus_gateway || true
        - docker run -dit --network host --name=ffc_janus_gateway jimber/ffc_janus_gateway:staging-$CI_COMMIT_TAG

production_build:
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc_janus production."
        - docker build -t jimber/ffc_janus_gateway:production-$CI_COMMIT_TAG .
        - docker push jimber/ffc_janus_gateway:production-$CI_COMMIT_TAG

production_deploy:
    stage: deploy
    when: manual
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcproduction
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc_janus production."
        - docker pull jimber/ffc_janus_gateway:production-$CI_COMMIT_TAG
        - docker rm -f ffc_janus_gateway || true
        - docker run -dit --network host --name=ffc_janus_gateway jimber/ffc_janus_gateway:production-$CI_COMMIT_TAG
