#caching modules
cache:
    paths:
      - node_modules/
      - .yarn
stages:
    - deploy

staging_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus staging."
        - docker rm -f ffc_janus_gateway || true
        - docker-compose build
        - docker-compose up -d

deploy:
    stage: deploy
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus production."
        - docker rm -f ffc_janus || true
        - docker-compose build
        - docker-compose up -d
    