cache:
    paths:
      - node_modules/
      - .yarn

stages:
    - build
    - deploy

staging_build:
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc_janus staging."
        - docker-compose build
        - docker-compose push

staging_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - ffcstaging
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc_janus staging."
        - docker rm -f ffc_janus_gateway || true
        - docker-compose pull
        - docker-compose up -d

production_build:
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Building ffc_janus production."
        - docker-compose build
        - docker-compose push

production_deploy:
    stage: deploy
    when: manual
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcproduction
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo "Deploying ffc_janus production."
        - docker rm -f ffc_janus_gateway || true
        - docker-compose pull
        - docker-compose up -d
