version: "3.3"
services:
  ffc_janus_gateway:
    build: .
    container_name: "ffc_janus_gateway"
    image: "jimber/ffc_janus_gateway-${ENVIRONMENT}:${CI_COMMIT_TAG}"
    network_mode: "host"
    restart: always
