version: '3'

services:
  janus_gateway:
    network_mode: "host"
    container_name: ffc_janus_gateway
    image: jimber/ffc_janus_gateway:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always